In [1]:
# Nominal data - there is no intrinsic order

In [2]:
# all columns in input side should be independent of each other

In [3]:
#multicollinearity - you cannot let your input cols to have mathematical relationship

In [6]:
# if we have n categories - we will have n cols after one hot encoding 
# then we remove one column from input side just to reduce the dimension and to handle multicollinearity

In [8]:
# Suppose we have a dataset of car brands and we perform One Hot Encoding.
# Then, instead of keeping separate columns for brands that occur very less frequently,
# we combine all those less frequent brands into a single category.
# This helps reduce the number of columns and makes the model simpler.

In [9]:
import numpy as np

In [10]:
import pandas as pd

In [11]:
df = pd.read_csv('cars.csv')

In [13]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [15]:
df.shape

(8128, 5)

df['brand'].value_counts()

In [17]:
df['brand'].nunique()

32

In [18]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

In [20]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

<h1>One hot encoding using pandas</h1>

In [21]:
pd.get_dummies(df, columns =['fuel', 'owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

<h1>K-1 One Hot Encoding</h1>

In [24]:
pd.get_dummies(df, columns =['fuel', 'owner'], drop_first = True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

In [26]:
# Pandas ko yaad nahi rehta ki which category was stored in which column.

In [27]:
# thats why we use sklearn ka class for it

In [28]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [29]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [37]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [38]:
# Pandas did not make any changes to the original columns during this process.

<h1>Using Sklearn</h1>

In [30]:
from sklearn.preprocessing import OneHotEncoder

In [32]:
ohe = OneHotEncoder(drop='first', sparse_output=False, dtype=np.int32)

In [40]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [41]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [42]:
X_train_new.shape

(6502, 7)

In [43]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], shape=(6502, 7), dtype=int32)

In [45]:
X_train[['brand', 'km_driven']].values

array([['Hyundai', 35000],
       ['Jeep', 60000],
       ['Hyundai', 25000],
       ...,
       ['Tata', 15000],
       ['Maruti', 32500],
       ['Isuzu', 121000]], shape=(6502, 2), dtype=object)

In [46]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], shape=(6502, 9), dtype=object)

In [47]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new)).shape

(6502, 9)

<h1>OneHotEncoding with Top Categories</h1>

In [48]:
counts = df['brand'].value_counts()

In [49]:
df['brand'].nunique()
threshold = 100

In [50]:
repl = counts[counts <= threshold].index

In [51]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
4597,False,False,False,False,False,False,True,False,False,False,False,False,False
2391,False,False,False,False,False,False,False,False,False,True,False,False,False
6474,False,False,False,False,False,False,False,True,False,False,False,False,False
2109,False,False,False,False,False,False,False,False,False,False,False,False,True
5655,False,False,False,False,False,False,False,False,False,True,False,False,False