In [3]:
import numpy as np
import pandas as pd

In [4]:
df = pd.read_csv('customer.csv')

In [5]:
df.sample(5)

    age  gender   review education purchased
37   94    Male  Average        PG       Yes
32   92    Male  Average        UG       Yes
2    70  Female     Good        PG        No
0    30  Female  Average    School        No
30   73    Male  Average        UG        No

In [6]:
# on review and educational encoding we will apply ordinal encoding

In [7]:
# on gender we will apply one hot encoding

In [8]:
df = df.iloc[:,2:]

In [9]:
df.head()

    review education purchased
0  Average    School        No
1     Poor        UG        No
2     Good        PG        No
3     Good        PG        No
4  Average        UG        No

In [10]:
from sklearn.model_selection import train_test_split

In [12]:
x_train, x_test, y_train, y_test = train_test_split(df.iloc[:,0:2], df.iloc[:,-1], test_size = 0.2)

In [13]:
x_train.sample(5)

     review education
36     Good        UG
1      Poor        UG
42     Good        PG
11     Good        UG
29  Average        UG

<h2>Ordinal Encoding</h2>

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
oe = OrdinalEncoder(categories= [['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [19]:
oe.fit(x_train)

OrdinalEncoder(categories=[['Poor', 'Average', 'Good'], ['School', 'UG', 'PG']])

In [20]:
x_train_transform = oe.transform(x_train)

In [21]:
x_test_transform = oe.transform(x_test)

In [22]:
x_train_transform

array([[0., 2.],
       [0., 0.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 2.],
       [0., 0.],
       [2., 2.],
       [2., 1.],
       [1., 0.],
       [2., 2.],
       [2., 1.],
       [0., 2.],
       [2., 1.],
       [0., 0.],
       [2., 0.],
       [1., 2.],
       [0., 2.],
       [2., 2.],
       [0., 2.],
       [1., 0.],
       [1., 1.],
       [0., 1.],
       [2., 0.],
       [2., 2.],
       [2., 1.],
       [1., 1.],
       [2., 2.]])

In [23]:
x_train_transform = pd.DataFrame(x_train_transform)

In [24]:
x_test_transform = pd.DataFrame(x_test_transform)

In [26]:
x_train_transform

      0    1
0   0.0  2.0
1   0.0  0.0
2   1.0  1.0
3   2.0  0.0
4   2.0  0.0
5   2.0  2.0
6   1.0  0.0
7   2.0  0.0
8   1.0  2.0
9   0.0  2.0
10  0.0  0.0
11  0.0  0.0
12  1.0  1.0
13  0.0  1.0
14  0.0  2.0
15  1.0  0.0
16  1.0  1.0
17  0.0  2.0
18  0.0  0.0
19  2.0  2.0
20  2.0  1.0
21  1.0  0.0
22  2.0  2.0
23  2.0  1.0
24  0.0  2.0
25  2.0  1.0
26  0.0  0.0
27  2.0  0.0
28  1.0  2.0
29  0.0  2.0
30  2.0  2.0
31  0.0  2.0
32  1.0  0.0
33  1.0  1.0
34  0.0  1.0
35  2.0  0.0
36  2.0  2.0
37  2.0  1.0
38  1.0  1.0
39  2.0  2.0

In [27]:
x_train_transform

      0    1
0   0.0  2.0
1   0.0  0.0
2   1.0  1.0
3   2.0  0.0
4   2.0  0.0
5   2.0  2.0
6   1.0  0.0
7   2.0  0.0
8   1.0  2.0
9   0.0  2.0
10  0.0  0.0
11  0.0  0.0
12  1.0  1.0
13  0.0  1.0
14  0.0  2.0
15  1.0  0.0
16  1.0  1.0
17  0.0  2.0
18  0.0  0.0
19  2.0  2.0
20  2.0  1.0
21  1.0  0.0
22  2.0  2.0
23  2.0  1.0
24  0.0  2.0
25  2.0  1.0
26  0.0  0.0
27  2.0  0.0
28  1.0  2.0
29  0.0  2.0
30  2.0  2.0
31  0.0  2.0
32  1.0  0.0
33  1.0  1.0
34  0.0  1.0
35  2.0  0.0
36  2.0  2.0
37  2.0  1.0
38  1.0  1.0
39  2.0  2.0

In [28]:
x_train_transform.describe()

               0          1
count  40.000000  40.000000
mean    1.025000   1.025000
std     0.861945   0.861945
min     0.000000   0.000000
25%     0.000000   0.000000
50%     1.000000   1.000000
75%     2.000000   2.000000
max     2.000000   2.000000

In [29]:
oe.categories_

[array(['Poor', 'Average', 'Good'], dtype=object),
 array(['School', 'UG', 'PG'], dtype=object)]

<h2>Label Encoding </h2>

<p>it is used only for output col</p>

In [31]:
from sklearn.preprocessing import LabelEncoder

In [32]:
le = LabelEncoder()

In [33]:
le.fit(y_train)

LabelEncoder()

In [34]:
le.classes_

array(['No', 'Yes'], dtype=object)

In [35]:
y_train = le.transform(y_train)

In [37]:
y_test = le.transform(y_test)

In [38]:
y_train

array([1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1])