In [1]:
import numpy as np 
import pandas as pd

In [2]:
date = pd.read_csv('orders.csv')

In [3]:
time = pd.read_csv('messages.csv')

In [5]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [6]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [8]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [9]:
# change datatype to date and time from string

In [10]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [11]:
date['date'] = pd.to_datetime(date['date'])

In [12]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

<h3>1. Extract Year</h3>

In [13]:
date['date_year'] = date['date'].dt.year

In [14]:
date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

In [15]:
# extracting month
date['date_month'] = date['date'].dt.month

In [16]:
date.head()

        date  product_id  city_id  orders  date_year  date_month
0 2019-12-10        5628       25       3       2019          12
1 2018-08-15        3646       14     157       2018           8
2 2018-10-23        1859       25       1       2018          10
3 2019-08-17        7292       25       1       2019           8
4 2019-01-06        4344       25       3       2019           1

In [17]:
date['date_month_name'] = date['date'].dt.month_name()

In [18]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

In [19]:
date['days'] = date['date'].dt.day

In [20]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

In [21]:
date['day_dow'] = date['date'].dt.dayofweek

In [22]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_dow
0,2019-12-10,5628,25,3,2019,12,December,10,1
1,2018-08-15,3646,14,157,2018,8,August,15,2
2,2018-10-23,1859,25,1,2018,10,October,23,1
3,2019-08-17,7292,25,1,2019,8,August,17,5
4,2019-01-06,4344,25,3,2019,1,January,6,6

In [25]:
date['day_dow_nmae'] = date['date'].dt.day_name()

In [26]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_dow,day_dow_nmae
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday

In [29]:
date['date_is_weekend'] = np.where(date['day_dow_nmae'].isin(['Sunday', 'Saturday']), 1, 0)

In [30]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_dow,day_dow_nmae,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1

In [31]:
# week of the year

In [33]:
date['week_of_year'] = date['date'].dt.isocalendar().week

In [34]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_dow,day_dow_nmae,date_is_weekend,week_of_year
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1

In [36]:
# quater of the year

In [37]:
date['quarter'] = date['date'].dt.quarter

In [38]:
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,days,day_dow,day_dow_nmae,date_is_weekend,week_of_year,quarter
0,2019-12-10,5628,25,3,2019,12,December,10,1,Tuesday,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,2,Wednesday,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,1,Tuesday,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,5,Saturday,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,6,Sunday,1,1,1

In [39]:
import datetime

today = datetime.datetime.today()

today

datetime.datetime(2026, 5, 31, 23, 34, 17, 957644)

In [40]:
today - date['date']

0     2364 days 23:34:17.957644
1     2846 days 23:34:17.957644
2     2777 days 23:34:17.957644
3     2479 days 23:34:17.957644
4     2702 days 23:34:17.957644
                 ...
995   2792 days 23:34:17.957644
996   2733 days 23:34:17.957644
997   2581 days 23:34:17.957644
998   2646 days 23:34:17.957644
999   2420 days 23:34:17.957644
Name: date, Length: 1000, dtype: timedelta64[ns]

In [41]:
(today - date['date']).dt.days

0      2364
1      2846
2      2777
3      2479
4      2702
       ...
995    2792
996    2733
997    2581
998    2646
999    2420
Name: date, Length: 1000, dtype: int64

In [43]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [44]:
time['date'] = pd.to_datetime(time['date'])

In [45]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [46]:
time['hour'] = time['date'].dt.hour
time['min'] = time['date'].dt.minute
time['sec'] = time['date'].dt.second

time.head()

,date,msg,hour,min,sec
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0

In [47]:
time['time'] = time['date'].dt.time

time.head()

,date,msg,hour,min,sec,time
0,2013-12-15 00:50:00,ищу на сегодня мужика 37,0,50,0,00:50:00
1,2014-04-29 23:40:00,ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826,23,40,0,23:40:00
2,2012-12-30 00:21:00,Днепр.м 43 позн.с д/ж *.о 067.16.34.576,0,21,0,00:21:00
3,2014-11-28 00:31:00,КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...,0,31,0,00:31:00
4,2013-10-26 23:11:00,Зая я тебя никогда не обижу люблю тебя!) Даше,23,11,0,23:11:00

In [48]:
today - time['date']

0     4550 days 22:44:17.957644
1     4414 days 23:54:17.957644
2     4900 days 23:13:17.957644
3     4202 days 23:03:17.957644
4     4600 days 00:23:17.957644
                 ...
995   5189 days 22:44:17.957644
996   4511 days 00:20:17.957644
997   4975 days 23:57:17.957644
998   5092 days 00:00:17.957644
999   4364 days 00:09:17.957644
Name: date, Length: 1000, dtype: timedelta64[ns]

In [49]:
(today - time['date'])/np.timedelta64(1,'s')

0      3.932019e+08
1      3.814557e+08
2      4.234436e+08
3      3.631358e+08
4      3.974414e+08
           ...
995    4.484115e+08
996    3.897516e+08
997    4.299262e+08
998    4.399488e+08
999    3.770502e+08
Name: date, Length: 1000, dtype: float64

In [50]:
(today - time['date'])/np.timedelta64(1,'h')

0      109222.738322
1      105959.904988
2      117623.221655
3      100871.054988
4      110400.388322
           ...
995    124558.738322
996    108264.338322
997    119423.954988
998    122208.004988
999    104736.154988
Name: date, Length: 1000, dtype: float64